# file: sonar-project.properties
sonar.projectKey=roboshop-catalogue
sonar.projectName=roboshop-catalogue
sonar.projectVersion=1.0.0
# source code is in current directory, that's why given .
sonar.sources=.
sonar.exclusions=jenkinsfile,**/node_modules/**,**/db/** 
